version: 2.1
orbs:
  node: circleci/node@7.2.1
  coveralls: coveralls/coveralls@2.2.5

jobs:
  build_and_test:
    executor: node/default
    environment:
      DATABASE_URL: file:./dev.db
      POKEAPI_URL: https://pokeapi.co/api/v2
      PORT: 5173
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npx prisma generate
          name: Generate Prisma Client
      - run:
          command: npm run test:cov
          name: Run tests with coverage
      - coveralls/upload
      - run:
          command: node --check src/app.js
          name: Check syntax
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
