version: 2.1
orbs:
  node: circleci/node@7.2.1
jobs:
  build_and_test: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    environment:
      DATABASE_URL: file:./dev.db
      POKEAPI_URL: https://pokeapi.co/api/v2
      PORT: 5173
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npx prisma generate
          name: Generate Prisma Client
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: node --check src/app.js
          name: Check syntax
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  build_test_deploy: # this can be any name you choose
    jobs:
      - build_and_test
